// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RTC_CMS.Models;

public partial class Areas
{
    public int Id { get; set; }

    public string AreaCode { get; set; }

    public string AreaName { get; set; }

    public int? ParentId { get; set; }
}