// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RTC_CMS.Models;

public partial class ErrorHistories
{
    public int Id { get; set; }

    public int? MachineId { get; set; }

    public int? MachineErrorId { get; set; }

    public DateTime? ErrorDate { get; set; }
}