// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RTC_CMS.Models;

public partial class MachineItems
{
    public int Id { get; set; }

    public string MachineItemCode { get; set; }

    public string MachineItemName { get; set; }

    public int? MachineId { get; set; }

    public decimal? OperateThreshold { get; set; }

    /// <summary>
    /// 1: Động cơ\n2: Biến tần
    /// </summary>
    public int? MachineItemType { get; set; }
}