// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RTC_CMS.Models;

public partial class MachineItemLink
{
    public int Id { get; set; }

    public int? MachineItemId { get; set; }

    public int? MachineItemVariantId { get; set; }

    public decimal? MinSpec { get; set; }

    public decimal? MaxSpec { get; set; }
}