// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RTC_CMS.Models;

public partial class MachineItemVariant
{
    public int Id { get; set; }

    public string VariantName { get; set; }

    /// <summary>
    /// 1: Nhiệt độ, 2: Độ rung, 3: Dòng điện, 4: Điện áp, 5: Tần số
    /// </summary>
    public int? VariantType { get; set; }
}