// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RTC_CMS.Models;

public partial class MachineAdressPlc
{
    public int Id { get; set; }

    public string AdressPlc { get; set; }

    public int? MachineItemId { get; set; }
}