// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RTC_CMS.Models;

public partial class Machines
{
    public int Id { get; set; }

    public string MachineCode { get; set; }

    public string MachineName { get; set; }

    public int? AreaId { get; set; }

    public decimal? OperateThreshold { get; set; }

    public string IpPlc { get; set; }

    public string PortPlc { get; set; }

    public int? StationNumber { get; set; }

    public string PlcadressSpeed { get; set; }
}