// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RTC_CMS.Models;

public partial class MachineErrors
{
    public int Id { get; set; }

    public string MachineErrorCode { get; set; }

    public string MachineErrorName { get; set; }
}