// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RTC_CMS.Models;

public partial class MaintenanceHistories
{
    public int Id { get; set; }

    public int? CreatedId { get; set; }

    public int? MachineItemId { get; set; }

    public string Content { get; set; }

    public DateTime? DateStartPlan { get; set; }

    public DateTime? DateEndPlan { get; set; }

    public DateTime? DateStartActual { get; set; }

    public DateTime? DateEndActual { get; set; }

    public int? AsignId { get; set; }

    public int? ApprovedId { get; set; }
    /// <summary>
    /// 1: chưa tiến hành, 2: đang tiến hành, 3: đã hoàn thành, 4: đã hủy bỏ
    /// </summary>
    public int? Status { get; set; }
}