// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RTC_CMS.Models;

public partial class OperateHistories
{
    public int Id { get; set; }

    public int? MachineItemLinkId { get; set; }

    /// <summary>
    /// 1: Chạy,2: Dừng,3: Lỗi
    /// </summary>
    public int? Status { get; set; }

    public decimal? RecordedValue { get; set; }

    public DateTime? RecordedAt { get; set; }
}